apiVersion: v1
kind: Service
metadata:
  name: springboot-load-balancer
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8081
    targetPort: 8080
    protocol: TCP
  selector:
    app: springboot
