apiVersion: v1
kind: Service
metadata:
  name: springboot-cluster-ip
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8082
    targetPort: 8080
    protocol: TCP
  selector:
    app: springboot