apiVersion: v1
kind: Service
metadata:
  name: springboot-node-port
spec:
  type: NodePort
  ports:
  - name: http
    port: 8083
    targetPort: 8080
    nodePort: 30001 
    protocol: TCP
  selector:
    app: springboot