apiVersion: v1
kind: Secret
metadata:
  name: springboot-secret
type: Opaque  
data:
  # encode base64 -> https://www.base64decode.org
  DB_USERNAME: cm9vdA==
  # encode base64 -> https://www.base64decode.org
  DB_PASSWORD: cGFzc3dvcmQ=